export const FETCHING_DATA = "FETCHING_DATA";

export const FETCH_DATA = "FETCH_DATA";
export const SAVE_DATA = "SAVE_DATA";
export const DELETE_DATA = "DELETE_DATA";
export const CREATE_DATA = "CREATE_DATA";

export const CHANGE_PROJECT_NAME = "CHANGE_PROJECT_NAME";
export const CHANGE_PROJECT_CODE = "CHANGE_PROJECT_CODE";
